export enum MusiccastCommands {
    JoinGroup = 'joingroup',
    LeaveGroup = 'leavegroup',
    AddClients = 'addclients',
    RemoveClients = 'removeclients',
    SetClients = 'setclients',
    Mute = 'mute',
    Next = 'next',
    Pause = 'pause',
    Play = 'play',
    Previous = 'previous',
    Sleep = 'sleep',
    Speak = 'speak',
    Stop = 'stop',
    SwitchTo = "switchto",
    Unmute = 'unmute',
    Volume = 'volume',
    VolumeDown = 'volumedown',
    VolumeUp = 'volumeup',
    Toggle = 'toggle',
    Power = 'power',
    Shuffle = 'shuffle',
    Repeat = 'repeat',
  }