export enum MusiccastCommands {
  JoinGroup = 'joingroup',
  LeaveGroup = 'leavegroup',
  AddClients = 'addclients',
  RemoveClients = 'removeclients',
  Clients = 'clients',
  Server = 'server',
  Mute = 'mute',
  Next = 'next',
  Pause = 'pause',
  Play = 'play',
  Previous = 'previous',
  Sleep = 'sleep',
  Speak = 'speak',
  Stop = 'stop',
  Input = "input",
  Unmute = 'unmute',
  Volume = 'volume',
  VolumeDown = 'volumedown',
  VolumeUp = 'volumeup',
  Power = 'power',
  Shuffle = 'shuffle',
  ToggleShuffle = 'toggleshuffle',
  Repeat = 'repeat',
  ToggleRepeat = 'togglerepeat',
}